AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  MatchingAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 3
      Role: 'arn:aws:iam::163651705262:role/service-role/Matching-API'
      Layers:
        - 'arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:4'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
